---
# tasks file for dotfiles

- name: setup vimrc
  copy:
    src: vimrc
    dest: "/home/{{ user }}/.vimrc"

- name: setup bashrc
  blockinfile:
    block: "{{ lookup('file', 'bashrc') }}"
    dest: "/home/{{ user }}/.bashrc"
    backup: true

- name: setup ssh-keys
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.ssh/"
    owner: "{{ user }}"
    mode: 0600
    backup: true
  with_fileglob:
    - "ssh/id_rsa*"

- name: setup ssh-config
  lineinfile:
    line: "{{ lookup('file', 'ssh/config') }}"
    dest: "/home/{{ user }}/.ssh/config"
    owner: "{{ user }}"
    mode: 0600
    backup: true

- name: setup ssh-config
  lineinfile:
    line: "{{ lookup('file', 'ssh/authorized_keys') }}"
    dest: "/home/{{ user }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    mode: 0600
    backup: true

# ==========================
# MANAGE PACKAGES
#===========================

- name: Remove apt-packages
  become: true
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ apt_absent }}"

- name: Install apt-packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_present }}"

- name: Install pip-packages
  pip:
    name: "{{ item }}"
    extra_args: --user --upgrade
  loop: "{{ pip_packages }}"

- name: Install snap-packages
  snap:
    name: "{{ item }}"
  loop: "{{ snap_packages }}"

- name: Install snap-packages with classic
  snap:
    name: "{{ item }}"
    classic: true
  loop: "{{ snap_packages_classic }}"