---
- name: Set up tinc
  hosts: localhost
  become: yes

  vars:
    hostname: dellusion
    netname: cloudnet
    pub_ip: 111.65.63.62
    subnet_ip: 10.100.1.4

  tasks:
    - name: Tinc is installed
      apt:
        name: tinc
        state: latest

    - name: Set up tinc-folders
      file:
        path: /etc/tinc/{{ netname }}/hosts
        state: directory
        owner: root
        group: root
        mode: u=rw,g=,o=

    - name: Configure tinc
      copy:
        dest: /etc/tinc/{{ netname }}/tinc.conf
        content: |
          Name = {{ hostname }}
          AddressFamily = ipv4
          Interface = tun0
          ConnectTo = {{ netname }}
        owner: root
        group: root
        mode: u=rw,g=,o=

    - name: Configure cloudnet hostconfig
      copy:
        dest: /etc/tinc/{{ netname }}/hosts/{{ netname }}
        content: |
          Address = sikanderlhote.com
          Subnet = 10.100.1.1

          -----BEGIN RSA PUBLIC KEY-----
          MIICCgKCAgEAy+TLeuFLGGwmG9YsnAPhbXnW6MDAKzMjyg6Nxbjzz/bmaJa/VR//
          k8tEjU3bgdalAkcYE2JdRKkYprhl8T1e1OtRShBN5ZGRF8Vm66kgMNLSoTfdBGm4
          eOnqlQk5lISq62PwcLfLu2RSNtVuTJ5qr51vaEOX3wjQwjlichOuU/NK7W0TL+H0
          LJDw4xRQIKj7PZJYEA949RuCKNEB8NZQXCJts1ROXa2T4P83iqkIzkd6MPaLsitO
          JtidahE2PAsja3k7Q5lLtD9cR8W3Ro59Xujk7Ph04TcJdUy3WMf4DKyErNicJ2Hf
          +GN9x+QdGOotc17/tIiGxLhD6ou9t7HjQdbo69wceek88tCDZBehJOXFREbYoS0c
          TJ6WqqZVDX2bsYlYVbov/v33sGnkq0SqlDehQsboLF6IrrmzR9S+AVKfGp9WuAHy
          +li8h0aQlzMHdiWIlH405JOGczmAwu2FCLNqI912OYyKnuzlmEC8x2p4E4fhh2wQ
          iNvoUdJkvN+J/iz9End62kC5ArnDnUrPitl3ypZsd35GYa4saRC1UKv/a0zTRIjL
          mKcD1fslss2WPzJMO9gij3hR+E3lWPef9/wdpBD+tpuW2QuGl5iw8XtD/Nxax1pY
          2Exl4dQ5r1Ni5t5q3JSkgdnK5m66hB7hYcMm6CIkboeukIV2pDogtd8CAwEAAQ==
          -----END RSA PUBLIC KEY-----
        owner: root
        group: root
        mode: u=rw,g=,o=

    - name: Configure local config
      copy:
        dest: /etc/tinc/{{ netname }}/hosts/{{ hostname }}
        content: |
          Address = {{ pub_ip }}
          Subnet = {{ subnet_ip }}
        owner: root
        group: root
        mode: u=rw,g=,o=

    - name: Configure tinc-up
      copy:
        dest: /etc/tinc/{{ netname }}/tinc-up
        content: |
          #!/bin/bash
          ip addr add {{ subnet_ip }}/24  dev $INTERFACE
          ip link set $INTERFACE up
        owner: root
        group: root
        mode: u=rwx,g=,o=

    - name: Configure tinc-up
      copy:
        dest: /etc/tinc/{{ netname }}/tinc-down
        content: |
          #!/bin/bash
          ip link set $INTERFACE down
        owner: root
        group: root
        mode: u=rwx,g=,o=